### ISSUE TITLE
eth.getWork is not supported

### ISSUE THREAD

**Issue by lehisnoe** [cryptozoic-io/go-cryptozoic#1]
Hello

I have running gvc 0.2.5 on linux. When I try to call method "eth_getWork" via RPC I've got:
```
$ curl -X POST --data '{"jsonrpc":"1.0","method":"eth_getWork","params":[],"id":1}' -H "Content-Type: application/json" http://127.0.0.1:8545
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"not supported"}}
```
The same responce I've got when eth.getWork() called via CLI:
```
> eth.getWork()
Error: not supported
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```

How should I call getWork via RPC?

Thanks

**Comment by lehisnoe** [comment]
Oh, I see that it works on 0.2.6

Thanks for fix
